server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /junto/ {
        try_files $uri $uri/ /junto/index.html;
    }

    location = / {
        return 301 /junto/;
    }
}
